name: Frontend CI

on:
  push:
    paths:
      - 'pwa-client/**'
  pull_request:
    paths:
      - 'pwa-client/**'

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./pwa-client

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: pwa-client/package-lock.json

      - name: Install Dependencies
        run: npm ci

      - name: Check code style and types
        run: npm run ci

      - name: Build Next.js application
        run: npm run build
